
all:
	true

install:
	install lyriczilla /usr/bin/
	install lrc2xml.py /usr/bin/

uninstall:
	rm /usr/bin/lyriczilla /usr/bin/lrc2xml.py

clean:
	rm -f *.o lyriczilla-bmp.so
	
rebuild:
	make clean all

